from PySide6.QtGui import QFont, QIcon
from PySide6.QtCore import QCoreApplication, QMetaObject, QRect,QSize, Qt
from PySide6.QtWidgets import QComboBox, QFrame, QHBoxLayout,QLineEdit, QPushButton, QScrollArea, QSizePolicy,QSpacerItem, QStackedWidget, QVBoxLayout, QWidget

class Ui_SearchPage(object):
    def setupUi(self, SearchPage):
        if not SearchPage.objectName():
            SearchPage.setObjectName(u"SearchPage")
        SearchPage.resize(1525, 942)
        self.horizontalLayout = QHBoxLayout(SearchPage)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.search_frame = QFrame(SearchPage)
        self.search_frame.setObjectName(u"search_frame")
        self.search_frame.setMinimumSize(QSize(400, 0))
        self.search_frame.setMaximumSize(QSize(400, 16777215))
        self.search_frame.setStyleSheet(u"background-color: white;")
        self.search_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.search_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.search_frame)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.searchback_frame = QFrame(self.search_frame)
        self.searchback_frame.setObjectName(u"searchback_frame")
        self.searchback_frame.setMinimumSize(QSize(0, 50))
        self.searchback_frame.setMaximumSize(QSize(300, 16777215))
        self.searchback_frame.setStyleSheet(u"background-color: white;")
        self.searchback_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.searchback_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_7 = QHBoxLayout(self.searchback_frame)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.back_Button = QPushButton(self.searchback_frame)
        self.back_Button.setObjectName(u"back_Button")
        self.back_Button.setMinimumSize(QSize(45, 45))
        self.back_Button.setMaximumSize(QSize(45, 45))
        font = QFont()
        font.setBold(False)
        font.setKerning(False)
        self.back_Button.setFont(font)
        self.back_Button.setStyleSheet(u"QPushButton {\n"
"	background-color: white;\n"
"	border:none;\n"
"	border-radius:22px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(237, 237, 238);\n"
"}")
        icon = QIcon()
        icon.addFile(u"icons/back.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.back_Button.setIcon(icon)
        self.back_Button.setIconSize(QSize(20, 20))
        self.back_Button.setCheckable(True)
        self.horizontalLayout_7.addWidget(self.back_Button)
        self.search_pushButton = QPushButton(self.searchback_frame)
        self.search_pushButton.setObjectName(u"search_pushButton")
        self.search_pushButton.setMinimumSize(QSize(50, 0))
        self.search_pushButton.setMaximumSize(QSize(50, 16777215))
        font1 = QFont()
        font1.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font1.setPointSize(15)
        font1.setBold(True)
        self.search_pushButton.setFont(font1)
        self.search_pushButton.setStyleSheet(u"QPushButton {\n"
"    border: none;\n"
"}\n"
"")
        self.horizontalLayout_7.addWidget(self.search_pushButton)
        self.verticalLayout_6.addWidget(self.searchback_frame, 0, Qt.AlignmentFlag.AlignLeft)
        self.frame = QFrame(self.search_frame)
        self.frame.setObjectName(u"frame")
        self.horizontalLayout_10 = QHBoxLayout(self.frame)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.search_lineEdit = QLineEdit(self.frame)
        self.search_lineEdit.setObjectName(u"search_lineEdit")
        self.search_lineEdit.setMinimumSize(QSize(0, 50))
        self.search_lineEdit.setMaximumSize(QSize(450, 16777215))
        self.search_lineEdit.setFont(font1)
        self.search_lineEdit.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.search_lineEdit.setStyleSheet(u"background-color: rgb(236, 230, 238);\n"
"border-radius:25px;\n"
"padding-left: 10px;\n"
"")
        self.horizontalLayout_10.addWidget(self.search_lineEdit)
        self.comboBox = QComboBox(self.frame)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setMinimumSize(QSize(0, 30))
        self.comboBox.setMaximumSize(QSize(16777215, 25))
        font2 = QFont()
        font2.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font2.setPointSize(15)
        self.comboBox.setFont(font2)
        self.comboBox.setStyleSheet(u"border-color:none;")
        self.horizontalLayout_10.addWidget(self.comboBox)
        self.verticalLayout_6.addWidget(self.frame)
        self.searchresult_scrollArea = QScrollArea(self.search_frame)
        self.searchresult_scrollArea.setObjectName(u"searchresult_scrollArea")
        self.searchresult_scrollArea.setStyleSheet(u"border:none;")
        self.searchresult_scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.searchresult_scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.searchresult_scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 381, 802))
        self.verticalLayout_10 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(5, 0, 0, 0)
        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(self.verticalSpacer_4)
        self.searchresult_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.searchresult_scrollArea)
        self.horizontalLayout.addWidget(self.search_frame)
        self.stackedWidget = QStackedWidget(SearchPage)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setStyleSheet(u"")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.retranslateUi(SearchPage)
        QMetaObject.connectSlotsByName(SearchPage)

    def retranslateUi(self, SearchPage):
        self.back_Button.setText("")
        self.search_pushButton.setText(QCoreApplication.translate("SearchPage", u"\u641c\u7d22", None))
        self.search_lineEdit.setPlaceholderText("")
        self.comboBox.setItemText(0, QCoreApplication.translate("SearchPage", u"\u52a8\u753b", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("SearchPage", u"\u4e66\u7c4d", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("SearchPage", u"\u6e38\u620f", None))
        pass