from PySide6.QtGui import QFont, QIcon
from PySide6.QtCore import QCoreApplication, QMetaObject, QSize, Qt
from PySide6.QtWidgets import QFrame, QHBoxLayout, QPushButton, QSizePolicy, QSpacerItem, QStackedWidget, QVBoxLayout, QWidget, QButtonGroup, QComboBox


class Ui_SettingsPage(object):
    def setupUi(self, SettingsPage):
        if not SettingsPage.objectName():
            SettingsPage.setObjectName(u"SettingsPage")
        SettingsPage.resize(1525, 942)
        self.horizontalLayout_8 = QHBoxLayout(SettingsPage)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.settings_frame = QFrame(SettingsPage)
        self.settings_frame.setObjectName(u"settings_frame")
        self.settings_frame.setMinimumSize(QSize(300, 0))
        self.settings_frame.setMaximumSize(QSize(300, 16777215))
        self.settings_frame.setStyleSheet(u"background-color: white;")
        self.settings_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.settings_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.settings_frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.Frame = QFrame(self.settings_frame)
        self.Frame.setObjectName(u"Frame")
        self.horizontalLayout = QHBoxLayout(self.Frame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.back_Button_2 = QPushButton(self.Frame)
        self.back_Button_2.setObjectName(u"back_Button_2")
        self.back_Button_2.setMinimumSize(QSize(45, 45))
        self.back_Button_2.setMaximumSize(QSize(45, 45))
        font = QFont()
        font.setBold(False)
        font.setKerning(False)
        self.back_Button_2.setFont(font)
        self.back_Button_2.setStyleSheet(u"QPushButton {\n"
"	background-color: white;\n"
"	border:none;\n"
"	border-radius:22px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(237, 237, 238);\n"
"}")
        icon = QIcon()
        icon.addFile(u"icons/back.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.back_Button_2.setIcon(icon)
        self.back_Button_2.setIconSize(QSize(20, 20))
        self.back_Button_2.setCheckable(True)
        self.horizontalLayout.addWidget(self.back_Button_2)
        self.setting_Button = QPushButton(self.Frame)
        self.setting_Button.setObjectName(u"setting_Button")
        self.setting_Button.setMinimumSize(QSize(175, 0))
        self.setting_Button.setMaximumSize(QSize(175, 16777215))
        font1 = QFont()
        font1.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font1.setPointSize(25)
        font1.setBold(True)
        self.setting_Button.setFont(font1)
        self.setting_Button.setStyleSheet(u"border:none")
        self.horizontalLayout.addWidget(self.setting_Button)
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(self.horizontalSpacer)
        self.verticalLayout.addWidget(self.Frame)
        self.Frame_2 = QFrame(self.settings_frame)
        self.Frame_2.setObjectName(u"Frame_2")
        self.verticalLayout_2 = QVBoxLayout(self.Frame_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(-1, 20, -1, -1)
        self.pushButton_3 = QPushButton(self.Frame_2)
        self.buttonGroup = QButtonGroup(SettingsPage)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.pushButton_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setMinimumSize(QSize(0, 50))
        self.pushButton_3.setMaximumSize(QSize(16777215, 50))
        font2 = QFont()
        font2.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font2.setPointSize(15)
        font2.setBold(True)
        self.pushButton_3.setFont(font2)
        self.pushButton_3.setStyleSheet(u"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0,20);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(233, 221, 255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border:none;\n"
"	border-radius: 10px;\n"
"}")
        self.pushButton_3.setCheckable(True)
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QPushButton(self.Frame_2)
        self.buttonGroup.addButton(self.pushButton_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setMinimumSize(QSize(0, 50))
        self.pushButton_4.setMaximumSize(QSize(16777215, 50))
        self.pushButton_4.setFont(font2)
        self.pushButton_4.setStyleSheet(u"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0,20);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(233, 221, 255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border:none;\n"
"	border-radius: 10px;\n"
"}")
        self.pushButton_4.setCheckable(True)
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.Frame_2)
        self.verticalSpacer = QSpacerItem(20, 866, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(self.verticalSpacer)
        self.horizontalLayout_8.addWidget(self.settings_frame)
        self.stackedWidget_2 = QStackedWidget(SettingsPage)
        self.stackedWidget_2.setObjectName(u"stackedWidget_2")
        self.stackedWidget_2.setStyleSheet(u"QStackedWidget {\n"
"    background-color: rgb(248, 242, 250);\n"
"}\n"
"\n"
"QStackedWidget > QWidget {\n"
"    background-color: transparent;\n"
"}")
        self.login_page = QWidget()
        self.login_page.setObjectName(u"login_page")
        self.login_page.setStyleSheet(u"")
        self.verticalLayout_7 = QVBoxLayout(self.login_page)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.pushButton = QPushButton(self.login_page)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setMinimumSize(QSize(0, 0))
        self.pushButton.setMaximumSize(QSize(16777215, 16777215))
        font3 = QFont()
        font3.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font3.setPointSize(17)
        font3.setBold(True)
        self.pushButton.setFont(font3)
        self.pushButton.setStyleSheet(u"border:none;")
        self.verticalLayout_7.addWidget(self.pushButton, 0, Qt.AlignmentFlag.AlignLeft)
        self.Frame_3 = QFrame(self.login_page)
        self.Frame_3.setObjectName(u"Frame_3")
        self.verticalLayout_4 = QVBoxLayout(self.Frame_3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(8, -1, -1, -1)
        self.pushButton_7 = QPushButton(self.Frame_3)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setMinimumSize(QSize(0, 30))
        self.pushButton_7.setMaximumSize(QSize(16777215, 30))
        font4 = QFont()
        font4.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font4.setPointSize(13)
        font4.setBold(True)
        self.pushButton_7.setFont(font4)
        self.pushButton_7.setStyleSheet(u"border:none")
        self.verticalLayout_4.addWidget(self.pushButton_7, 0, Qt.AlignmentFlag.AlignLeft)
        self.pushButton_2 = QPushButton(self.Frame_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        font5 = QFont()
        font5.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font5.setPointSize(13)
        font5.setBold(False)
        self.pushButton_2.setFont(font5)
        self.pushButton_2.setStyleSheet(u"border:none;")
        self.verticalLayout_4.addWidget(self.pushButton_2, 0, Qt.AlignmentFlag.AlignLeft)
        self.pushButton_9 = QPushButton(self.Frame_3)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setFont(font5)
        self.pushButton_9.setStyleSheet(u"border:none;")
        self.verticalLayout_4.addWidget(self.pushButton_9, 0, Qt.AlignmentFlag.AlignLeft)
        self.pushButton_8 = QPushButton(self.Frame_3)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setFont(font5)
        self.pushButton_8.setStyleSheet(u"border:none;")
        self.verticalLayout_4.addWidget(self.pushButton_8, 0, Qt.AlignmentFlag.AlignLeft)
        self.login_Button = QPushButton(self.Frame_3)
        self.login_Button.setObjectName(u"login_Button")
        self.login_Button.setFont(font5)
        self.login_Button.setStyleSheet(u"")
        self.verticalLayout_4.addWidget(self.login_Button, 0, Qt.AlignmentFlag.AlignLeft)
        self.collection_Button = QPushButton(self.Frame_3)
        self.collection_Button.setObjectName(u"collection_Button")
        self.collection_Button.setFont(font5)
        self.collection_Button.setStyleSheet(u"")
        self.verticalLayout_4.addWidget(self.collection_Button, 0, Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_7.addWidget(self.Frame_3)
        self.Frame_4 = QFrame(self.login_page)
        self.Frame_4.setObjectName(u"Frame_4")
        self.horizontalLayout_2 = QHBoxLayout(self.Frame_4)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(8, 1, -1, -1)
        self.pushButton_12 = QPushButton(self.Frame_4)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setMinimumSize(QSize(0, 30))
        self.pushButton_12.setMaximumSize(QSize(16777215, 30))
        self.pushButton_12.setFont(font4)
        self.pushButton_12.setStyleSheet(u"border:none")
        self.horizontalLayout_2.addWidget(self.pushButton_12, 0, Qt.AlignmentFlag.AlignLeft)
        self.comboBox = QComboBox(self.Frame_4)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox, 0, Qt.AlignmentFlag.AlignLeft)
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)
        self.verticalLayout_7.addWidget(self.Frame_4)
        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(self.verticalSpacer_3)
        self.stackedWidget_2.addWidget(self.login_page)
        self.pikpak_page = QWidget()
        self.pikpak_page.setObjectName(u"pikpak_page")
        self.verticalLayout_3 = QVBoxLayout(self.pikpak_page)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.pushButton_5 = QPushButton(self.pikpak_page)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setMinimumSize(QSize(0, 0))
        self.pushButton_5.setMaximumSize(QSize(16777215, 16777215))
        font6 = QFont()
        font6.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font6.setPointSize(20)
        font6.setBold(True)
        self.pushButton_5.setFont(font6)
        self.pushButton_5.setStyleSheet(u"border:none;")
        self.verticalLayout_3.addWidget(self.pushButton_5, 0, Qt.AlignmentFlag.AlignLeft)
        self.frame_2 = QFrame(self.pikpak_page)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_9 = QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.pushButton_6 = QPushButton(self.frame_2)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setFont(font4)
        self.pushButton_6.setStyleSheet(u"border:none;")
        self.verticalLayout_9.addWidget(self.pushButton_6, 0, Qt.AlignmentFlag.AlignLeft)
        self.pushButton_10 = QPushButton(self.frame_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setFont(font4)
        self.pushButton_10.setStyleSheet(u"border:none;")
        self.verticalLayout_9.addWidget(self.pushButton_10, 0, Qt.AlignmentFlag.AlignLeft)
        self.pushButton_11 = QPushButton(self.frame_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setFont(font4)
        self.pushButton_11.setStyleSheet(u"border:none;")
        self.verticalLayout_9.addWidget(self.pushButton_11, 0, Qt.AlignmentFlag.AlignLeft)
        self.login_Button_2 = QPushButton(self.frame_2)
        self.login_Button_2.setObjectName(u"login_Button_2")
        self.login_Button_2.setMinimumSize(QSize(0, 30))
        self.login_Button_2.setFont(font4)
        self.login_Button_2.setStyleSheet(u"")
        self.verticalLayout_9.addWidget(self.login_Button_2, 0, Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalSpacer_2 = QSpacerItem(20, 759, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(self.verticalSpacer_2)
        self.stackedWidget_2.addWidget(self.pikpak_page)
        self.horizontalLayout_8.addWidget(self.stackedWidget_2)
        self.retranslateUi(SettingsPage)
        self.stackedWidget_2.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(SettingsPage)

    def retranslateUi(self, SettingsPage):
        self.back_Button_2.setText("")
        self.setting_Button.setText(QCoreApplication.translate("SettingsPage", u"\u8bbe\u7f6e", None))
        self.pushButton_3.setText(QCoreApplication.translate("SettingsPage", u"Bangumi", None))
        self.pushButton_4.setText(QCoreApplication.translate("SettingsPage", u"PikPak", None))
        self.pushButton.setText(QCoreApplication.translate("SettingsPage", u"Bangumi", None))
        self.pushButton_7.setText(QCoreApplication.translate("SettingsPage", u"Bangumi \u6388\u6743", None))
        self.pushButton_2.setText(QCoreApplication.translate("SettingsPage", u"ID", None))
        self.pushButton_9.setText(QCoreApplication.translate("SettingsPage", u"Access Token", None))
        self.pushButton_8.setText(QCoreApplication.translate("SettingsPage", u"Refresh Token", None))
        self.login_Button.setText(QCoreApplication.translate("SettingsPage", u"\u5f00\u59cb\u6388\u6743", None))
        self.collection_Button.setText(QCoreApplication.translate("SettingsPage", u"\u83b7\u53d6\u6536\u85cf", None))
        self.pushButton_12.setText(QCoreApplication.translate("SettingsPage", u"Bangumi \u57df\u540d \uff1a", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("SettingsPage", u"bangumi.tv", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("SettingsPage", u"bgm.tv", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("SettingsPage", u"chii.in", None))
        self.pushButton_5.setText(QCoreApplication.translate("SettingsPage", u"PikPak \u767b\u5f55", None))
        self.pushButton_6.setText(QCoreApplication.translate("SettingsPage", u"username", None))
        self.pushButton_10.setText(QCoreApplication.translate("SettingsPage", u"password", None))
        self.pushButton_11.setText(QCoreApplication.translate("SettingsPage", u"encoded token", None))
        self.login_Button_2.setText(QCoreApplication.translate("SettingsPage", u"\u5f00\u59cb\u767b\u5f55", None))
        pass