from PySide6.QtGui import QFont, QIcon
from PySide6.QtCore import QCoreApplication, QMetaObject, QRect, QSize, Qt
from PySide6.QtWidgets import QFrame, QHBoxLayout, QPushButton,QSizePolicy, QSpacerItem, QStackedWidget, QVBoxLayout, QWidget

class Ui_SettingsPage(object):
    def setupUi(self, SettingsPage):
        if not SettingsPage.objectName():
            SettingsPage.setObjectName(u"SettingsPage")
        SettingsPage.resize(1525, 942)
        self.horizontalLayout_8 = QHBoxLayout(SettingsPage)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.settinfs_frame = QFrame(SettingsPage)
        self.settinfs_frame.setObjectName(u"settinfs_frame")
        self.settinfs_frame.setMinimumSize(QSize(300, 0))
        self.settinfs_frame.setMaximumSize(QSize(300, 16777215))
        self.settinfs_frame.setStyleSheet(u"background-color: white;")
        self.settinfs_frame.setFrameShape(QFrame.StyledPanel)
        self.settinfs_frame.setFrameShadow(QFrame.Raised)
        self.login_frame = QFrame(self.settinfs_frame)
        self.login_frame.setObjectName(u"login_frame")
        self.login_frame.setGeometry(QRect(70, 20, 120, 80))
        self.login_frame.setFrameShape(QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QFrame.Raised)
        self.name_Button = QPushButton(self.login_frame)
        self.name_Button.setObjectName(u"name_Button")
        self.name_Button.setGeometry(QRect(30, 40, 75, 23))
        self.name_Button.setStyleSheet(u"border:none")
        self.back_Button_2 = QPushButton(self.settinfs_frame)
        self.back_Button_2.setObjectName(u"back_Button_2")
        self.back_Button_2.setGeometry(QRect(10, 30, 45, 45))
        self.back_Button_2.setMinimumSize(QSize(45, 45))
        self.back_Button_2.setMaximumSize(QSize(45, 45))
        font = QFont()
        font.setBold(False)
        font.setKerning(False)
        self.back_Button_2.setFont(font)
        self.back_Button_2.setStyleSheet(u"QPushButton {\n"
"	background-color: white;\n"
"	border:none;\n"
"	border-radius:22px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(237, 237, 238);\n"
"}")
        icon = QIcon()
        icon.addFile(u"icons/back.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.back_Button_2.setIcon(icon)
        self.back_Button_2.setIconSize(QSize(20, 20))
        self.back_Button_2.setCheckable(True)
        self.horizontalLayout_8.addWidget(self.settinfs_frame)
        self.stackedWidget_2 = QStackedWidget(SettingsPage)
        self.stackedWidget_2.setObjectName(u"stackedWidget_2")
        self.stackedWidget_2.setStyleSheet(u"background-color: rgb(248, 242, 250);")
        self.login_page = QWidget()
        self.login_page.setObjectName(u"login_page")
        self.login_page.setStyleSheet(u"")
        self.verticalLayout_7 = QVBoxLayout(self.login_page)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.pushButton = QPushButton(self.login_page)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setMinimumSize(QSize(0, 0))
        self.pushButton.setMaximumSize(QSize(16777215, 16777215))
        font1 = QFont()
        font1.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font1.setPointSize(20)
        font1.setBold(True)
        self.pushButton.setFont(font1)
        self.pushButton.setStyleSheet(u"border:none;")
        self.verticalLayout_7.addWidget(self.pushButton, 0, Qt.AlignLeft)
        self.frame = QFrame(self.login_page)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(0, 100))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_8 = QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setObjectName(u"pushButton_2")
        font2 = QFont()
        font2.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font2.setPointSize(10)
        font2.setBold(True)
        self.pushButton_2.setFont(font2)
        self.pushButton_2.setStyleSheet(u"border:none;")
        self.verticalLayout_8.addWidget(self.pushButton_2, 0, Qt.AlignLeft)
        self.pushButton_10 = QPushButton(self.frame)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setFont(font2)
        self.pushButton_10.setStyleSheet(u"border:none;")
        self.verticalLayout_8.addWidget(self.pushButton_10, 0, Qt.AlignLeft)
        self.pushButton_9 = QPushButton(self.frame)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setFont(font2)
        self.pushButton_9.setStyleSheet(u"border:none;")
        self.verticalLayout_8.addWidget(self.pushButton_9, 0, Qt.AlignLeft)
        self.pushButton_8 = QPushButton(self.frame)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setFont(font2)
        self.pushButton_8.setStyleSheet(u"border:none;")
        self.verticalLayout_8.addWidget(self.pushButton_8, 0, Qt.AlignLeft)
        self.login_Button = QPushButton(self.frame)
        self.login_Button.setObjectName(u"login_Button")
        self.login_Button.setFont(font2)
        self.login_Button.setStyleSheet(u"")
        self.verticalLayout_8.addWidget(self.login_Button, 0, Qt.AlignLeft)
        self.collection_Button = QPushButton(self.frame)
        self.collection_Button.setObjectName(u"collection_Button")
        self.collection_Button.setFont(font2)
        self.collection_Button.setStyleSheet(u"")
        self.verticalLayout_8.addWidget(self.collection_Button, 0, Qt.AlignLeft)
        self.verticalLayout_7.addWidget(self.frame)
        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(self.verticalSpacer_3)
        self.stackedWidget_2.addWidget(self.login_page)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.horizontalLayout_8.addWidget(self.stackedWidget_2)
        self.retranslateUi(SettingsPage)
        QMetaObject.connectSlotsByName(SettingsPage)

    def retranslateUi(self, SettingsPage):
        self.name_Button.setText(QCoreApplication.translate("SettingsPage", u"\u8bbe\u7f6e", None))
        self.back_Button_2.setText("")
        self.pushButton.setText(QCoreApplication.translate("SettingsPage", u"Bangumi \u540c\u6b65", None))
        self.pushButton_2.setText(QCoreApplication.translate("SettingsPage", u"ID", None))
        self.pushButton_10.setText(QCoreApplication.translate("SettingsPage", u"Token\uff1a\u70b9\u51fb\u6d4b\u8bd5\u8fde\u901a\u6027", None))
        self.pushButton_9.setText(QCoreApplication.translate("SettingsPage", u"Access Token", None))
        self.pushButton_8.setText(QCoreApplication.translate("SettingsPage", u"Refresh Token", None))
        self.login_Button.setText(QCoreApplication.translate("SettingsPage", u"\u5f00\u59cb\u6388\u6743", None))
        self.collection_Button.setText(QCoreApplication.translate("SettingsPage", u"\u83b7\u53d6\u6536\u85cf", None))
        pass